// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/oauth.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	ResponseType         string   `protobuf:"bytes,2,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	RedirectUrl          string   `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *AuthRequest) GetResponseType() string {
	if m != nil {
		return m.ResponseType
	}
	return ""
}

func (m *AuthRequest) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func (m *AuthRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type AuthResponse struct {
	RedirectTo           string   `protobuf:"bytes,1,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetRedirectTo() string {
	if m != nil {
		return m.RedirectTo
	}
	return ""
}

type AccessTokenRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessTokenRequest) Reset()         { *m = AccessTokenRequest{} }
func (m *AccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AccessTokenRequest) ProtoMessage()    {}
func (*AccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{2}
}

func (m *AccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenRequest.Unmarshal(m, b)
}
func (m *AccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *AccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenRequest.Merge(m, src)
}
func (m *AccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AccessTokenRequest.Size(m)
}
func (m *AccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenRequest proto.InternalMessageInfo

func (m *AccessTokenRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AccessTokenRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType            string   `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	IdToken              string   `protobuf:"bytes,6,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{3}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Token) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type Identity struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	UnionId              string   `protobuf:"bytes,2,opt,name=UnionId,proto3" json:"UnionId,omitempty"`
	Nick                 string   `protobuf:"bytes,3,opt,name=Nick,proto3" json:"Nick,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=Source,proto3" json:"Source,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{4}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *Identity) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *Identity) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Identity) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Identity) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Identity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AccessTokenResponse struct {
	Token                *Token    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Identity             *Identity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Raw                  string    `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AccessTokenResponse) Reset()         { *m = AccessTokenResponse{} }
func (m *AccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AccessTokenResponse) ProtoMessage()    {}
func (*AccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{5}
}

func (m *AccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessTokenResponse.Unmarshal(m, b)
}
func (m *AccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *AccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessTokenResponse.Merge(m, src)
}
func (m *AccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AccessTokenResponse.Size(m)
}
func (m *AccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccessTokenResponse proto.InternalMessageInfo

func (m *AccessTokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AccessTokenResponse) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *AccessTokenResponse) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

type RefreshTokenRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{6}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{7}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type ProfileRequest struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{8}
}

func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ProfileResponse struct {
	Raw                  string    `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Identity             *Identity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_036c345ae9233cf0, []int{9}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *ProfileResponse) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "edge.oauth.v1.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "edge.oauth.v1.AuthResponse")
	proto.RegisterType((*AccessTokenRequest)(nil), "edge.oauth.v1.AccessTokenRequest")
	proto.RegisterType((*Token)(nil), "edge.oauth.v1.Token")
	proto.RegisterType((*Identity)(nil), "edge.oauth.v1.Identity")
	proto.RegisterType((*AccessTokenResponse)(nil), "edge.oauth.v1.AccessTokenResponse")
	proto.RegisterType((*RefreshTokenRequest)(nil), "edge.oauth.v1.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "edge.oauth.v1.RefreshTokenResponse")
	proto.RegisterType((*ProfileRequest)(nil), "edge.oauth.v1.ProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "edge.oauth.v1.ProfileResponse")
}

func init() { proto.RegisterFile("v1/oauth.proto", fileDescriptor_036c345ae9233cf0) }

var fileDescriptor_036c345ae9233cf0 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xf3, 0xd9, 0x8c, 0xd3, 0x82, 0xb6, 0x11, 0x84, 0xa0, 0x02, 0x75, 0x2f, 0x88, 0x43,
	0xaa, 0x26, 0x37, 0x0e, 0xa0, 0x14, 0x21, 0x91, 0x0b, 0x45, 0x21, 0x15, 0x88, 0x4b, 0x64, 0xec,
	0x29, 0x59, 0x35, 0x78, 0xcd, 0x7a, 0x13, 0xc8, 0x91, 0x1b, 0xbf, 0x80, 0x9f, 0xc3, 0x95, 0xbf,
	0x85, 0x76, 0x77, 0xd6, 0x71, 0x92, 0x52, 0x44, 0x6f, 0x9e, 0x99, 0x37, 0x6f, 0xde, 0x9b, 0xb1,
	0x0d, 0x7b, 0x8b, 0x93, 0x63, 0x11, 0xce, 0xd5, 0xb4, 0x9b, 0x4a, 0xa1, 0x04, 0xdb, 0xc5, 0xf8,
	0x13, 0x76, 0x6d, 0x66, 0x71, 0x12, 0x7c, 0xf7, 0xc0, 0x1f, 0xcc, 0xd5, 0x74, 0x84, 0x5f, 0xe6,
	0x98, 0x29, 0xd6, 0x82, 0x6a, 0x16, 0x89, 0x14, 0xdb, 0xde, 0x23, 0xef, 0x71, 0x63, 0x64, 0x03,
	0x76, 0x04, 0xbb, 0x12, 0xb3, 0x54, 0x24, 0x19, 0x4e, 0xd4, 0x32, 0xc5, 0x76, 0xc9, 0x54, 0x9b,
	0x2e, 0x39, 0x5e, 0xa6, 0xc8, 0x0e, 0xa1, 0x29, 0x31, 0xe6, 0x12, 0x23, 0x35, 0x99, 0xcb, 0x59,
	0xbb, 0x6c, 0x30, 0xbe, 0xcb, 0x9d, 0xcb, 0x99, 0x61, 0x57, 0xa1, 0xc2, 0x76, 0x85, 0xd8, 0x75,
	0x10, 0x1c, 0x43, 0xd3, 0x4a, 0xb0, 0x64, 0xec, 0x21, 0xe4, 0x4d, 0x13, 0x25, 0x48, 0x09, 0xb8,
	0xd4, 0x58, 0x04, 0xcf, 0x80, 0x0d, 0xa2, 0x08, 0xb3, 0x6c, 0x2c, 0x2e, 0x31, 0x71, 0xd2, 0x19,
	0x54, 0x22, 0x11, 0x3b, 0xe5, 0xe6, 0x79, 0x35, 0xb0, 0x54, 0x1c, 0xf8, 0xcb, 0x83, 0xaa, 0x69,
	0xd5, 0x9a, 0x43, 0xc3, 0x34, 0x51, 0x3a, 0xa6, 0x5e, 0x3f, 0x5c, 0xb1, 0x5b, 0xef, 0x17, 0x12,
	0xb3, 0x29, 0x61, 0x72, 0xef, 0x26, 0x69, 0x41, 0xf9, 0xda, 0xca, 0xc5, 0xb5, 0x1d, 0x00, 0xe0,
	0xb7, 0x94, 0x4b, 0xcc, 0x26, 0x3c, 0x31, 0x9e, 0xcb, 0xa3, 0x06, 0x65, 0x86, 0x89, 0x2e, 0x1b,
	0x46, 0xbb, 0xd2, 0xaa, 0xe9, 0x6c, 0x98, 0x8c, 0xd9, 0xe7, 0x3d, 0xd8, 0xe1, 0x31, 0xcd, 0xac,
	0x99, 0x62, 0x9d, 0xc7, 0x66, 0x5c, 0xf0, 0xd3, 0x83, 0x9d, 0x61, 0x8c, 0x89, 0xe2, 0x6a, 0xc9,
	0xee, 0x40, 0xed, 0x2c, 0xc5, 0x64, 0x18, 0x93, 0x7a, 0x8a, 0x58, 0x1b, 0xea, 0xe7, 0x09, 0x17,
	0xba, 0x60, 0x25, 0xbb, 0x50, 0x6f, 0xea, 0x35, 0x8f, 0x2e, 0x49, 0xac, 0x79, 0xd6, 0x2c, 0x6f,
	0xc5, 0x5c, 0x46, 0xee, 0x36, 0x14, 0xe9, 0xfc, 0x60, 0x11, 0xaa, 0x50, 0x92, 0x40, 0x8a, 0xb4,
	0xe3, 0x97, 0x9f, 0x43, 0x3e, 0x23, 0x69, 0x36, 0x08, 0x7e, 0x78, 0xb0, 0xbf, 0x76, 0x1a, 0x3a,
	0xe9, 0x13, 0xa8, 0xae, 0x16, 0xec, 0xf7, 0x5a, 0xdd, 0xb5, 0xb7, 0xb0, 0x6b, 0xc1, 0x16, 0xc2,
	0xfa, 0xda, 0xb7, 0xf5, 0x66, 0x84, 0xfb, 0xbd, 0xbb, 0x1b, 0x70, 0x67, 0x7d, 0x94, 0x03, 0xd9,
	0x6d, 0x28, 0xcb, 0xf0, 0x2b, 0x39, 0xd2, 0x8f, 0xc1, 0x53, 0xd8, 0x1f, 0x15, 0x4e, 0xe4, 0xde,
	0x92, 0xad, 0x73, 0x7a, 0xdb, 0xe7, 0x0c, 0x4e, 0xa1, 0xb5, 0xde, 0xfb, 0xff, 0x36, 0x82, 0x3e,
	0xec, 0xbd, 0x91, 0xe2, 0x82, 0xcf, 0xd0, 0x8d, 0xfe, 0xf7, 0xcb, 0x16, 0xbc, 0x87, 0x5b, 0x79,
	0x13, 0xcd, 0x24, 0x67, 0x5e, 0xee, 0xec, 0x46, 0x0b, 0xea, 0xfd, 0x2e, 0x81, 0x7f, 0xa6, 0x3f,
	0xb3, 0x17, 0x33, 0x8e, 0x89, 0x62, 0xcf, 0xa1, 0xa2, 0x23, 0xd6, 0xd9, 0x68, 0x2d, 0xfc, 0x0c,
	0x3a, 0xf7, 0xaf, 0xac, 0x91, 0xae, 0x31, 0xf8, 0x85, 0x4b, 0xb3, 0xc3, 0x4d, 0xec, 0xd6, 0x07,
	0xda, 0x09, 0xae, 0x83, 0x10, 0xeb, 0x3b, 0x68, 0x16, 0x37, 0xcf, 0x36, 0x7b, 0xae, 0x38, 0x69,
	0xe7, 0xe8, 0x5a, 0x0c, 0x11, 0xbf, 0x82, 0x3a, 0x6d, 0x96, 0x1d, 0x6c, 0xe0, 0xd7, 0xcf, 0xd4,
	0x79, 0xf0, 0xb7, 0xb2, 0x65, 0x3a, 0xad, 0x7e, 0x28, 0x87, 0x29, 0xff, 0x58, 0x33, 0xff, 0xd3,
	0xfe, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xae, 0x95, 0xdf, 0x61, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OAuthClientClient is the client API for OAuthClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OAuthClientClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	AccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type oAuthClientClient struct {
	cc *grpc.ClientConn
}

func NewOAuthClientClient(cc *grpc.ClientConn) OAuthClientClient {
	return &oAuthClientClient{cc}
}

func (c *oAuthClientClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/edge.oauth.v1.OAuthClient/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClientClient) AccessToken(ctx context.Context, in *AccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/edge.oauth.v1.OAuthClient/AccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClientClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/edge.oauth.v1.OAuthClient/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthClientClient) Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/edge.oauth.v1.OAuthClient/Profile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthClientServer is the server API for OAuthClient service.
type OAuthClientServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	AccessToken(context.Context, *AccessTokenRequest) (*AccessTokenResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	Profile(context.Context, *ProfileRequest) (*ProfileResponse, error)
}

// UnimplementedOAuthClientServer can be embedded to have forward compatible implementations.
type UnimplementedOAuthClientServer struct {
}

func (*UnimplementedOAuthClientServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedOAuthClientServer) AccessToken(ctx context.Context, req *AccessTokenRequest) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessToken not implemented")
}
func (*UnimplementedOAuthClientServer) RefreshToken(ctx context.Context, req *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedOAuthClientServer) Profile(ctx context.Context, req *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}

func RegisterOAuthClientServer(s *grpc.Server, srv OAuthClientServer) {
	s.RegisterService(&_OAuthClient_serviceDesc, srv)
}

func _OAuthClient_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthClientServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.oauth.v1.OAuthClient/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthClientServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthClient_AccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthClientServer).AccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.oauth.v1.OAuthClient/AccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthClientServer).AccessToken(ctx, req.(*AccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthClient_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthClientServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.oauth.v1.OAuthClient/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthClientServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthClient_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthClientServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edge.oauth.v1.OAuthClient/Profile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthClientServer).Profile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OAuthClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edge.oauth.v1.OAuthClient",
	HandlerType: (*OAuthClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _OAuthClient_Auth_Handler,
		},
		{
			MethodName: "AccessToken",
			Handler:    _OAuthClient_AccessToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _OAuthClient_RefreshToken_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _OAuthClient_Profile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/oauth.proto",
}
